### ISSUE TITLE
Zig 0.12 support?

### ISSUE THREAD

**Issue by Speykious** [the-argus/zig-compile-commands#5]
This is a really nice project! I essentially use Zig as a build system for a C project of mine, and so I use compile-commands so that clang can understand what I'm doing.

A few days ago I tried to port it to Zig 0.12, but I hit a roadblock at some point, probably because I'm not very familiar with Zig myself. Do you plan to add support for 0.12?

**Comment by the-argus** [comment]
@Speykious I stopped using zig for a long while but I am back now. Just updated to 0.13.0 :)
